application:
  jwt:
    secretKey: "bjdksaDSYAGDYUbSHADbsajkDBIdHJsbadhjbhdjasbdhjLBHASJDBGiaDBJHKsbaHJDBhjsakbhdjabsaBDGHYUiaL"
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml